spring.application.name=demo-course

# disable JPA
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# enable devtools
spring.devtools.restart.enabled=true
spring.devtools.add-properties=false
